version: '3.9'

services:
  webapp2:
    build: ./WebApplication2
    restart: always
    depends_on:
      - app_db
    ports:
      - 8083:8080
    environment:
      - ConnectionStrings__DefaultConnection=USER ID=postgres;Password=postgres;Server=app_db;Port=5432;Database=Directories; IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=https://+:8080
        
  app_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Directories
    ports:
      - 5433:5432
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      start_period: 30s
        
volumes:
  app_data: